# Generated by Django 3.2.4 on 2021-10-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20211020_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active_en',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active_fr',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active_ru',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
    ]
