# Generated by Django 3.2.4 on 2021-10-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20211020_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_active_en',
            field=models.BooleanField(default=True, verbose_name='Активная'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_active_fr',
            field=models.BooleanField(default=True, verbose_name='Активная'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_active_ru',
            field=models.BooleanField(default=True, verbose_name='Активная'),
        ),
        migrations.AddField(
            model_name='discount',
            name='is_active_en',
            field=models.BooleanField(default=True, verbose_name='Активная'),
        ),
        migrations.AddField(
            model_name='discount',
            name='is_active_fr',
            field=models.BooleanField(default=True, verbose_name='Активная'),
        ),
        migrations.AddField(
            model_name='discount',
            name='is_active_ru',
            field=models.BooleanField(default=True, verbose_name='Активная'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_active_en',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_active_fr',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_active_ru',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_active_en',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_active_fr',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_active_ru',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
    ]
