# Generated by Django 3.2.4 on 2021-10-20 15:05

from django.db import migrations
import django_resized.forms
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20211020_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_photos',
            name='main_photo_xxl2',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', help_text='Формат файла: jpg, jpeg или png. Ограничение размера: 3 Мбайт.', keep_meta=True, quality=80, size=[2400, 1800], upload_to=shop.models.get_file_path, verbose_name='Картинка'),
        ),
    ]
